### ISSUE TITLE
client crash - storage drawers

### ISSUE THREAD

**Issue by dewboy3d** [ftog-thorgal/Avant#5]
I used packing tape on a storage drawer and crashed. now every time I try to log into the ftog server my client crashes with the following error.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/27/16 10:35 PM
Description: Rendering Block Entity

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.WorldRenderer.func_178977_d(WorldRenderer.java:535)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.jaquadro.minecraft.chameleon.render.ChamRender.renderPartialFaceColorMult(ChamRender.java:247)
	at com.jaquadro.minecraft.chameleon.render.ChamRender.renderPartialFace(ChamRender.java:231)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderTape(TileEntityDrawersRenderer.java:365)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderUpgrades(TileEntityDrawersRenderer.java:279)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderTileEntityAt(TileEntityDrawersRenderer.java:115)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.func_180535_a(TileEntityDrawersRenderer.java:35)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:678)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.WorldRenderer.func_178977_d(WorldRenderer.java:535)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.jaquadro.minecraft.chameleon.render.ChamRender.renderPartialFaceColorMult(ChamRender.java:247)
	at com.jaquadro.minecraft.chameleon.render.ChamRender.renderPartialFace(ChamRender.java:231)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderTape(TileEntityDrawersRenderer.java:365)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderUpgrades(TileEntityDrawersRenderer.java:279)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderTileEntityAt(TileEntityDrawersRenderer.java:115)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.func_180535_a(TileEntityDrawersRenderer.java:35)

-- Block Entity Details --
Details:
	Name: storagedrawers:basicDrawers // com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard
	Block type: ID #1860 (tile.basicDrawers // com.jaquadro.minecraft.storagedrawers.block.BlockDrawers)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-519,67,373), Chunk: (at 9,4,5 in -33,23; contains blocks -528,0,368 to -513,255,383), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Actual block type: ID #1860 (tile.basicDrawers // com.jaquadro.minecraft.storagedrawers.block.BlockDrawers)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:678)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['dewboy3d'/7258542, l='MpServer', x=-519.92, y=67.00, z=376.47]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 83.00,94.00,-18.00 - World: (83,94,-18), Chunk: (at 3,5,14 in 5,-2; contains blocks 80,0,-32 to 95,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 4868265 game time, 339067 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityCow['Cow'/7258604, l='MpServer', x=-590.59, y=68.00, z=302.63], EntityCreeper['Creeper'/7258599, l='MpServer', x=-594.47, y=17.53, z=365.50], EntityPig['Pig'/7258595, l='MpServer', x=-478.56, y=64.00, z=306.53], EntityCreeper['Creeper'/7259107, l='MpServer', x=-458.50, y=40.00, z=321.50], EntityPig['Pig'/7258588, l='MpServer', x=-490.50, y=65.00, z=305.00], EntityAuraNode['Aura Node'/7258589, l='MpServer', x=-538.50, y=68.50, z=452.50], EntityAuraNode['Aura Node'/7258586, l='MpServer', x=-550.50, y=81.50, z=436.50], EntityPlayerSP['dewboy3d'/7258542, l='MpServer', x=-519.92, y=67.00, z=376.47], EntityPig['Pig'/7258587, l='MpServer', x=-482.47, y=63.00, z=307.66], EntityCreeper['Creeper'/7258584, l='MpServer', x=-535.41, y=64.00, z=347.00], EntityPig['Pig'/7258585, l='MpServer', x=-520.69, y=68.00, z=311.53], EntityBackpack['entity.ironbackpacks.EntityBackpack.name'/7258582, l='MpServer', x=-519.92, y=67.00, z=376.47], EntityZombie['Zombie'/7258583, l='MpServer', x=-532.72, y=18.09, z=408.28], EntityCreeper['Creeper'/7258609, l='MpServer', x=-533.53, y=49.00, z=302.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1690681368 bytes (1612 MB) / 3701473280 bytes (3530 MB) up to 4121952256 bytes (3931 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4421m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1794 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1794.jar) 
	UCHIJA	Forge{11.15.1.1794} [Minecraft Forge] (forge-1.8.9-11.15.1.1794.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJA	OpenComputers|Core{1.6.0.2-beta.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJA	ActuallyAdditions{1.8.9-r26} [Actually Additions] (ActuallyAdditions-1.8.9-r26.jar) 
	UCHIJA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJA	agricraft{2.0.0a} [AgriCraft] (agricraft-2.0.0a.jar) 
	UCHIJA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJA	ArmorHud{1.0.0} [ArmorHud] (ArmorHud-1.8.9-1.0.0.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.4.1} [Aroma1997Core|Helper] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8.9-1.1.2.0.jar) 
	UCHIJA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJA	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UCHIJA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJA	Automagy{2.0.1} [Automagy] (Automagy-1.8.9-2.0.1.jar) 
	UCHIJA	basemetals{1.7.4} [Base Metals] (BaseMetals-1.7.4.jar) 
	UCHIJA	bdlib{1.10.0.31} [BD Lib] (bdlib-1.10.0.31-mc1.8.9.jar) 
	UCHIJA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1935-universal.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	UCHIJA	BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
	UCHIJA	bookshelfapi{2.3.7} [Bookshelf] (Bookshelf-API-1.8.9-2.3.7.jar) 
	UCHIJA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJA	Chameleon{1.8.9-1.1.1} [Chameleon] (Chameleon-1.8.9-1.1.1.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJA	chiselsandbits{8.6} [Chisels & Bits] (chiselsandbits-8.6.jar) 
	UCHIJA	ChiselsBytes{0.2} [Chisels & Bytes] (ChiselsBytes-1.8.9-0.2.jar) 
	UCHIJA	clayworldgen{v1.0.0} [Clay WorldGen] (ClayWorldGen-1.0.1.jar) 
	UCHIJA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
	UCHIJA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHIJA	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCHIJA	deepresonance{1.1.4beta19} [DeepResonance] (deepresonance-1.8.9-1.1.4beta19.jar) 
	UCHIJA	eirairc{4.9.12} [EiraIRC] (eirairc-mc1.8.9-4.9.12.jar) 
	UCHIJA	poweradvantage{1.5.4} [Power Advantage] (PowerAdvantage-1.5.4.jar) 
	UCHIJA	electricadvantage{1.1.2} [Electric Advantage] (ElectricAdvantage-1.1.2.jar) 
	UCHIJA	enderrift{0.10.0} [Ender-Rift] (EnderRift-0.10.0.jar) 
	UCHIJA	enderutilities{0.5.0} [Ender Utilities] (enderutilities-1.8.9-0.5.0.jar) 
	UCHIJA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJA	pressure{1.3.0.25} [Pressure Pipes] (pressure-1.3.0.25-mc1.8.9.jar) 
	UCHIJA	advgenerators{0.9.19.9} [Advanced Generators] (generators-0.9.19.9-mc1.8.9.jar) 
	UCHIJA	gravestone{1.1.3} [Gravestone] (Gravestone Mod 1.1.3.jar) 
	UCHIJA	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCHIJA	HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
	UCHIJA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJA	ironbackpacks{1.8.9-2.0.5} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.5.jar) 
	UCHIJA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCHIJA	llor{1.0.7-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.8.9.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJA	moarcarts{2.0.1-16} [MoarCarts] (moarcarts-1.8.9-2.0.1-16.jar) 
	UCHIJA	modtweaker2{1.0.0} [Mod Tweaker 2] (ModTweaker2-1.0.0.jar) 
	UCHIJA	numina{0.5.0-001} [Numina] (Numina-0.5.0-001.jar) 
	UCHIJA	powersuits{0.11.0-003} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.8.9-0.11.0-003.jar) 
	UCHIJA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
	UCHIJA	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurntiureModv3.6.1(1.8.9).jar) 
	UCHIJA	tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
	UCHIJA	neotech{2.4.4} [NeoTech] (NeoTech-1.8.9-2.4.4.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar) 
	UCHIJA	notenoughwands{1.3.0} [Not Enough Wands] (notenoughwands-1.8.9-1.3.0.jar) 
	UCHIJA	OpenComputers{1.6.0.2-beta.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar) 
	UCHIJA	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCHIJA	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UCHIJA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJA	xreliquary{1.3.1.222} [Reliquary] (Reliquary-1.3.1.222.jar) 
	UCHIJA	reptilemod{3.1.0} [Reptile Mod] (reptilemod-1.8.9-3.2.1-40.jar) 
	UCHIJA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJA	rftools{4.23beta35} [RFTools] (rftools-1.8.9-4.23beta35.jar) 
	UCHIJA	rftoolsdim{4.22beta30} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta30.jar) 
	UCHIJA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.8.8.jar) 
	UCHIJA	routerreborn{1.8.9-3.0.5.14b_universal} [Router Reborn] (RouterReborn-1.8.9-3.0.5.14b_universal.jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UCHIJA	SGCraft{1.11.0} [Greg's SG Craft] (SGCraft-1.11.0-mc1.8.9.jar) 
	UCHIJA	steamadvantage{1.5.3} [Steam Advantage] (SteamAdvantage-1.5.3.jar) 
	UCHIJA	StorageDrawers{1.8.9-2.6.0} [Storage Drawers] (StorageDrawers-1.8.9-2.6.0.jar) 
	UCHIJA	storagenetwork{1.8.1} [Storage Network] (StorageNetwork-1.8.9-1.8.1.jar) 
	UCHIJA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCHIJA	witherchargingfix{1.0.0} [Wither Charging Fix] (witherchargingfix-1.8.9-1.0.0-0-universal.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* ActuallyAdditionsAPI (8) from ActuallyAdditions-1.8.9-r26.jar
		* AgriCraftAPI (1.0) from agricraft-2.0.0a.jar
		* Baubles|API (1.1.1.0) from Baubles-1.8.9-1.1.3.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.8.9-2.0.0-20.jar
		* BotaniaAPI (77) from Botania-unofficial.r1.8-299.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-8.6.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ActuallyAdditions-1.8.9-r26.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ActuallyAdditions-1.8.9-r26.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from EnderRift-0.10.0.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.8.9-1.1.4beta19.jar
		* EiraIRC|API (2.0) from eirairc-mc1.8.9-4.9.12.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.8.9-1.4.247.jar
		* GameAnalyticsAPI (1.2) from AuraCascade-592.jar
		* HydCraft|API (1.0) from HydCraft-1.8.9-3.1.65-universal.jar
		* IronBackpacks|API (0.4) from IronBackpacks-1.8.9-2.0.5.jar
		* jeresources|API (0.4.0) from JustEnoughResources-1.8.9-0.4.0.jar
		* journeymap|client-api (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-display (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-event (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-model (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* journeymap|client-api-util (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.9.176.jar
		* McJtyLib (1.8.9-1.8.1beta10) from mcjtylib-1.8.9-1.8.1beta10.jar
		* moarcarts|API (1.0) from moarcarts-1.8.9-2.0.1-16.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.8.9-1.6.0.2-beta.1.jar
		* PneumaticCraftApi (1.0) from PneumaticCraft-1.8.9-1.13.8-12-universal.jar
		* pressureAPI (1.3.0.25) from pressure-1.3.0.25-mc1.8.9.jar
		* PsiAPI (1) from Psi-beta-23.jar
		* SchematicaAPI (1.1) from Schematica-1.8.9-1.7.7.143-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.8.9-1.7.7.143-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.6.0.jar
		* Thaumcraft|API (5.2.3.0) from Thaumcraft-1.8.9-5.2.4.jar
		* WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
	Launched Version: forge-11.15.1.1794
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz`
```

**Comment by ftog-thorgal** [comment]
Removed storage drawers in the area via MCEdit, was able to visit area without crashing.
